### ISSUE TITLE
panel-cover__title panel-title iUp上的字体怎样才能去掉呀？

### ISSUE THREAD

**Issue by NianBroken** [dmego/dmegohome.github.io#11]
我把`assets\css\`的`vno.css`的7951行注释掉以后
重新刷新缓存
他还是会加载那个字体……
就算我把7951行整个删了，它也会加载……
![image](https://user-images.githubusercontent.com/57057288/151738542-39b9785d-20a0-4386-95c9-adef93fb1d6a.png)

**Comment by dmego** [comment]
@NianBroken 这一行 [index.html#L14](https://github.com/dmego/home.github.io/blob/c2cb81d48bb211bfcac424bd173313373ebea621/index.html#L14) 换成你自己本地的样式
