### ISSUE TITLE
感谢作者无私分享

### ISSUE THREAD

**Issue by immoke** [dmego/dmegohome.github.io#12]
非常喜欢您的主页风格，个人也拷贝了一份搭建了自己的首页，非常感谢。

请问，如果想自己定义首页的一句话语句，能否指导一下修改思路？谢谢。
调用官方库，毕竟不是自己想分享的话。

**Comment by dmego** [comment]
@immoke 如果想要自定义，需要有下面两个步骤：
- 把代码 [/assets/js/main.js](https://github.com/dmego/home.github.io/blob/34df2d172629224acefd2ce2a0ab7c120049559e/assets/js/main.js#L50) 的第 `51` 行到 `57` 行注释。
- 在文件 [/index.html](https://github.com/dmego/home.github.io/blob/34df2d172629224acefd2ce2a0ab7c120049559e/index.html#L57) 的 `57` 行自定义 `一句话`, `59` 行自定义 `作者`

**Comment by immoke** [comment]
> @immoke 如果想要自定义，需要有下面两个步骤：
> 
> * 把代码 [/assets/js/main.js](https://github.com/dmego/home.github.io/blob/34df2d172629224acefd2ce2a0ab7c120049559e/assets/js/main.js#L50) 的第 `51` 行到 `57` 行注释。
> * 在文件 [/index.html](https://github.com/dmego/home.github.io/blob/34df2d172629224acefd2ce2a0ab7c120049559e/index.html#L57) 的 `57` 行自定义 `一句话`, `59` 行自定义 `作者`

您好，请问，如果想做成跟您主页类似的，也是多个语句随机循环呢？麻烦再指导一下，非常感谢~
最近一直在研究自建语句库的hitokoto-api，感觉，如果只是几句至十几句的话，搭建一套小系统有些大材小用了~
继续求指导，感谢！

**Comment by dmego** [comment]
@immoke 小例子，可以参考一下：
- 把代码 [/assets/js/main.js](https://github.com/dmego/home.github.io/blob/34df2d172629224acefd2ce2a0ab7c120049559e/assets/js/main.js#L48) 的第 `48` 行开始的函数 `$(document).ready(function ()` 换成如下的示例。

```js
$(document).ready(function () {
	var desLocal = [];
	desLocal[0] = { 'hitokoto': '云想衣裳花想容, 春风拂槛露华浓', 'from': '李白' };
	desLocal[1] = { 'hitokoto': '爱,其实很简单, 困难的是去接受它。', 'from': '网络' };
	desLocal[2] = { 'hitokoto': '我喝过你喝的西北风, 这算不算很穷', 'from': '网络' };
	desLocal[3] = { 'hitokoto': '宇宙是蚂蚁的梦', 'from': 'Jack' };
	desLocal[4] = { 'hitokoto': '你的笑像一条恶犬, 撞乱了我心弦', 'from': '盗将行' };
	var indexName = "des-local-index";
	var index = sessionStorage.getItem(indexName);
	if (isNaN(index) || index == 4) index = 0;
	else index++;
	var e = desLocal[index];
	$('#description').html(e.hitokoto + "<br/> -「<strong>" + e.from + "</strong>」")
	sessionStorage.setItem(indexName, index);

	$(".iUp").each(function (i, e) {
		iUp.up(e);
	});

	$(".js-avatar")[0].onload = function () {
		$(".js-avatar").addClass("show");
	}
});
```
- 注意文件 [/index.html](https://github.com/dmego/home.github.io/blob/34df2d172629224acefd2ce2a0ab7c120049559e/index.html#L129) 的 `129` 行 需要改成使用本地的 `main.js` 文件：
```html
<script type="text/javascript" src="./assets/js/main.js"></script>
```

**Comment by immoke** [comment]
按照您的方法实现了，万分感谢！

**Comment by immoke** [comment]
作者您好，按照您的方式，index++，可以实现语句的顺序输出，我在网上搜索了一下，整合成可以随机输出的，还请您点评。


	function randomFrom(min,max)
	{
		return Math.floor(Math.random() * (max - min + 1) + min);
	}

	$(document).ready(function () {
		var desLocal = [];
		desLocal[0] = { 'hitokoto': '0)刺猬没有刺的那一面，只打算留给喜欢它的人', 'from': '网络' };
		desLocal[1] = { 'hitokoto': '1)柏邦妮：心里有很多苦的人，要多少甜才填得满啊？<br>马东：你错了邦妮，心里有很多苦的人，一点点甜就能填满。', 'from': '《奇葩说》' };	
		desLocal[2] = { 'hitokoto': '2)喜欢一个人的时候，哪个又不是烂命一条。', 'from': '老狗《风犬少年的天空》' };
		desLocal[3] = { 'hitokoto': '3)后来 我总算学会了 如何去爱<br>可惜 你早已远去 消失在人海<br>后来 终于在眼泪中 明白<br>有些人 一旦错过 就不在', 'from': '刘若英《后来》' };	
		desLocal[4] = { 'hitokoto': '4)爱而不得，才是人生常态', 'from': '网络' };
		desLocal[5] = { 'hitokoto': '5)所谓御世制人，就是你可以参透整个世界，却永远无法了解人性。', 'from': '邵庄《毛骗 终结篇》' };
		desLocal[6] = { 'hitokoto': '6)既然相遇是偶然，又何必在意分开时的突然呢。', 'from': '邵庄《毛骗 终结篇》' };
		var indexName = "des-local-index";
		var index = randomFrom(0,6);
		var e = desLocal[index];
		$('#description').html(e.hitokoto + "<br/> -「<strong>" + e.from + "</strong>」")
		sessionStorage.setItem(indexName, index);

		$(".iUp").each(function (i, e) {
			iUp.up(e);
		});

		$(".js-avatar")[0].onload = function () {
			$(".js-avatar").addClass("show");
		}
	});

**Comment by dmego** [comment]
@immoke 👍🏻
