### ISSUE TITLE
背景主题等无法显示，只有文字和链接

### ISSUE THREAD

**Issue by Ekkone** [dmego/dmegohome.github.io#16]

**Comment by dmego** [comment]
估计是 jsdelivr 的问题，换成了 unpkg 现在应该可以了。

**Comment by Ekkone** [comment]
现在又有出现同样的情况，但是开了全局代理之后可以正常，不代理就没有背景主题，这个是因为某个服务被墙了导致的吗？

**Comment by dmego** [comment]
背景图片请求的是 www.bing.com 这个网址，可以看看不开代理能不能打开

**Comment by Ekkone** [comment]
bing是可以正常打开，但是打开这个网页就是这样：
![image](https://github.com/dmego/home.github.io/assets/38444906/7fbf8a89-8701-4e87-8bde-91e5414e394b)

**Comment by dmego** [comment]
可以用手机打开试试，看看是不是网络问题，现在壁纸的地址已经换成了 cn.bing.com

**Comment by Ekkone** [comment]
奇怪，同样的wifi网络，手机的确可以正常打开，电脑浏览器就不行，换了浏览器也不行，好玄学
