### ISSUE TITLE
可以添加一个搜索栏嘛？

### ISSUE THREAD

**Issue by Akoasmn** [dmego/dmegohome.github.io#18]
翻来翻去感觉作者的这个主页最好看，如果能加一个导航就更好啦！

**Comment by dmego** [comment]
@ZhangXQA 可以说具体点吗，需要搜索栏搜啥内容？

**Comment by Akoasmn** [comment]
大概可以添加一个必应搜索，个人是觉得加一个搜索栏会更加美观。其实已经很好看了
