### ISSUE TITLE
1

### ISSUE THREAD

**Issue by jinnan11** [dmego/dmegohome.github.io#27]
1

**Comment by 3152598423** [comment]
> 用梯子访问正常，不用梯子只显示文字 ![Screenshot_2023-08-22-22-00-32-180_com microsoft emmx](https://user-images.githubusercontent.com/52593036/262376257-26e49cbd-581d-44fc-822d-b58bcd3cd9e4.jpg) ![Screenshot_2023-08-22-21-57-41-032_com microsoft emmx](https://user-images.githubusercontent.com/52593036/262376191-89a578ba-695e-42b1-ace7-d39016c5f43c.jpg)
