### ISSUE TITLE
这个很棒的个人主页如何自定义本地文件夹的背景呢？

### ISSUE THREAD

**Issue by i-iooi-i** [dmego/dmegohome.github.io#3]
大佬你好，无意中在知乎看到有小编推荐这个主页，所以找过来的。

它很棒！只是对随机背景图的不可控问题有些疑惑。想了解一下如何通过修改，然后如何随机显示定义好的背景图呢？比如我将一部分背景图放在img文件夹，我想这样更可控页面观感。

非常感谢提供这么棒的项目。

**Comment by dmego** [comment]
可以参考 [main.js#L54](https://github.com/dmego/home.github.io/blob/cb203ee5ed460fa0e8394b03161bd60872c44bf0/assets/js/main.js#L54) 的代码逻辑，这里的 `imgUrls` 是从`Bing壁纸API`获取的图片 URL 数组，你可以换成你自定义的
