### ISSUE TITLE
如何增加新的icon图标

### ISSUE THREAD

**Issue by ahhuipt** [dmego/dmegohome.github.io#31]
您的主页很好看，感谢分享，那个阿里巴巴网站注册了，但是不太会操作，尝试了好多次图标都没加上

**Comment by dmego** [comment]
iconfont 官方提供了[使用说明](https://www.iconfont.cn/help/detail?spm=a313x.help_detail.i3.29.50e23a81RiTNeV&helptype=code)，可以参考改一下`iconfont.css` 这个文件
