### ISSUE TITLE
GitHub Action 已经按照教程操作了。如何并更新 images.json 文件

### ISSUE THREAD

**Issue by ahhuipt** [dmego/dmegohome.github.io#32]
GitHub Action 已经按照教程操作了，我是把你的网页搭建到服务器上的，请问如何每天获取 Bing 壁纸 URL 并更新 images.json 文件，不太会操作

**Comment by dmego** [comment]
看一下 Github 官方的[`GitHub Action`](https://docs.github.com/zh/actions)使用文档,里面写的非常详细
