### ISSUE TITLE
如何更换英文的字体，能否提供一个样式对照表

### ISSUE THREAD

**Issue by drfy** [dmego/dmegohome.github.io#33]
感谢 感谢

**Comment by dmego** [comment]
改一下`vno.css`文件里面 `.panel-title` 的 `font-family`；目前css文件都是压缩后的，可以格式化后再修改

**Comment by drfy** [comment]
我知道这里改，但是不是改成啥名字，这个字体是本地的还是在线引用的，支持哪些英文字体



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Dmego ***@***.***&gt;
发送时间: 2024年4月22日 10:04
收件人: dmego/home.github.io ***@***.***&gt;
抄送: drfy ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [dmego/home.github.io] 如何更换英文的字体，能否提供一个样式对照表 (Issue #33)





 
改一下vno.css文件里面 .panel-title 的 font-family；目前css文件都是压缩后的，可以格式化后再修改

**Comment by dmego** [comment]
普通的字体按照规范直接改就行；如果是特殊的字体，需要下载到本地，然后像`onlinewebfonts.css`文件一样引入一下
