### ISSUE TITLE
是否有其它的方法获取必应壁纸？

### ISSUE THREAD

**Issue by sheenisme** [dmego/dmegohome.github.io#35]
你好，采用GitHub Action似乎仓库每天都会多一个提交，所以不太想要这种方式？请问是否还有别的方式获取必应壁纸呢？

**Comment by dmego** [comment]
找到一种能解决前端跨域问题的方案就行；之前用过使用了`Yahoo Query Language (YQL)`和`JsonBird`，不过现在都不能用了，所以才用的`GitHub Action`

**Comment by sheenisme** [comment]
嗯嗯，好的，谢谢。我试一下~
