### ISSUE TITLE
请问如何增加新的 icon 样式?

### ISSUE THREAD

**Issue by jarvanstack** [dmego/dmegohome.github.io#6]
请问如何增加新的 icon 样式?
能否给个教程, 谢谢
![image](https://user-images.githubusercontent.com/60028085/135426055-311ed5c7-241d-4fc9-85c4-7ba6b025c3fc.png)

**Comment by dmego** [comment]
@dengjiawen8955  可以在这个网站上自定义 https://www.iconfont.cn/
